version: "3.8"
services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/matheustodao/mongodb/database:/data/db
    ports:
      - 27027:27027
    restart: unless-stopped
